name: Tests and Dependabot PR Handling

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  # Verifies the boilerplate can start and run in GitHub Actions environment
  test-for-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: prebuild android
        run: |
          npm install
          npx expo prebuild --platform android
  
      - name: Install Dependencies
        run: |
          cd android && ./gradlew dependencies
  
      - name: Build Debug APK
        run: |
          cd android && ./gradlew assembleDebug